language: php

dist: bionic

env:
    global:
        - APP_ENV=test

jobs:
    include:
        -   &behat
            stage: test
            name: "Behat tests (PHP 7.3)"

            sudo: false

            php: 7.3
            env: SYLIUS_CACHE_DIR=$HOME/.sylius-cache SYLIUS_BUILD_DIR=etc/build PHP_VERSION="7.3"

            cache:
                yarn: true
                directories:
                - ~/.composer/cache/files
                - $SYLIUS_CACHE_DIR

            services:
                - memcached
                - mysql

            before_install:
                - phpenv config-rm xdebug.ini || true

                - echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
                - pecl update-channels
                - printf "yes\n" | pecl install memcached

                - mkdir -p tests/Application/public/media/image/
                - cp migrations/* tests/Application/src/Migrations/

            install:
                - composer update --no-interaction --prefer-dist
                - (cd tests/Application && yarn install)

            before_script:
                - (cd tests/Application && bin/console doctrine:database:create -vvv)
                - (cd tests/Application && bin/console doctrine:migrations:migrate -n -vvv -q)
                - (cd tests/Application && bin/console assets:install -vvv)
                - (cd tests/Application && bin/console cache:warmup -vvv)
                - (cd tests/Application && yarn build)

                # Configure display
                - sudo apt-get update && sudo apt-get install libgconf-2-4 -y
                - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1680x1050x16
                - export DISPLAY=:99

                # Download Symfony command
                - wget https://get.symfony.com/cli/installer -O - | bash

                # Download and configure ChromeDriver
                - |
                    if [ ! -f $SYLIUS_CACHE_DIR/chromedriver ] || [ "$($SYLIUS_CACHE_DIR/chromedriver --version | grep -c 2.34)" = "0" ]; then
                        curl http://chromedriver.storage.googleapis.com/2.34/chromedriver_linux64.zip > chromedriver.zip
                        unzip chromedriver.zip
                        chmod +x chromedriver
                        mv chromedriver $SYLIUS_CACHE_DIR
                    fi
                # Run ChromeDriver
                - $SYLIUS_CACHE_DIR/chromedriver > /dev/null 2>&1 &

                # Download and configure Selenium
                - |
                    if [ ! -f $SYLIUS_CACHE_DIR/selenium.jar ] || [ "$(java -jar $SYLIUS_CACHE_DIR/selenium.jar --version | grep -c 3.4.0)" = "0" ]; then
                        curl http://selenium-release.storage.googleapis.com/3.4/selenium-server-standalone-3.4.0.jar > selenium.jar
                        mv selenium.jar $SYLIUS_CACHE_DIR
                    fi
                # Run Selenium
                - java -Dwebdriver.chrome.driver=$SYLIUS_CACHE_DIR/chromedriver -jar $SYLIUS_CACHE_DIR/selenium.jar > /dev/null 2>&1 &

                # Run webserver
                - (cd tests/Application && /home/travis/.symfony/bin/symfony server:start --port=8080 --dir=public --allow-http --no-tls --force-php-discovery --daemon)

            script:
                - composer validate --strict
                - composer analyse

                - vendor/bin/phpunit
                - vendor/bin/behat --strict -vvv --no-interaction --tags="~@todo" || vendor/bin/behat --strict -vvv --no-interaction --rerun --tags="~@todo"

            after_failure:
                - vendor/lakion/mink-debug-extension/travis/tools/upload-textfiles "${SYLIUS_BUILD_DIR}/*.log"
        -   <<: *behat
            php: 7.4
            env: SYLIUS_CACHE_DIR=$HOME/.sylius-cache SYLIUS_BUILD_DIR=etc/build PHP_VERSION="7.4"
            name: "Behat tests (PHP 7.4)"
        -   &phpspec
            stage: test
            php: 7.3
            name: "PHPSpec (with code coverage, php 7.3)"

            sudo: false

            services:
                - memcached

            before_install:
                - phpenv config-rm xdebug.ini || true

                - echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
                - pecl update-channels
                - printf "yes\n" | pecl install memcached

            install:
                - composer update --no-interaction --prefer-dist

            script:
                - phpdbg -qrr vendor/bin/phpspec run
        -   <<: *phpspec
            php: 7.4
            name: "PHPSpec (with code coverage, php 7.4)"

